### ISSUE TITLE
phoneFormat wasn't working properly for XXX-XXX-XXXX

### ISSUE THREAD

**Issue by kremerNK** [levidavidmurray/input-formatter#1]
I am new to github and programming in general, so pardon if this is the incorrect way to go about this

Your formatter worked as expected with `const phoneFormat = '({0}{1}{2}) {3}{4}{5}-{6}{7}{8}{9}';`, the default value you have set,  but it wouldn't work 100% correctly for `phoneFormat = '{0}{1}{2}-{3}{4}{5}-{6}{7}{8}{9}';`. I altered phoneFormat to 

`const phoneFormat = '{0}{1}{2}-{3}{4}{5}-{6}{7}{8}{9}';`

and while inputting values to field, a `-}` would appear after the third digit. the `-` is expected, but the `}` was not. With another number entry, the `}` disappeared and was replaced with the expected keydown value. The formatter properly formats the 6th digit to only insert `-`.  `}` is not inserted here, so it seems to work properly here. The `}` that is inserted at the 4th index does not need to be manipulated to be erased, it simply erases when a number is entered. But a user may be confused by the sudden appearance of `}`. It's probably easier to understand what I'm saying by just trying it. Use `const phoneFormat = '{0}{1}{2}-{3}{4}{5}-{6}{7}{8}{9}';` and see the behavior of the html input field. 

I manipulated a few lines of the formatter like a monkey and figured out that if I change 

`replaceIndex += 2;` to `replaceIndex +=1`, that it will format xxx-xxx-xxxx correctly, without the appearance of `}` in the input field. This change seems to maintain the proper function of other variations of phoneFormat, at least as far as I have checked. 

Thanks for putting your formatter here. I think this problem would have taken me a long time to solve!

**Comment by levidavidmurray** [comment]
Hey! I did an overhaul on the whole formatting api. It's a bit more complicated, but a lot more configurable.

You can install the dependency using `npm install @levidavidmurray/input-formatter` or `yarn add @levidavidmurray/input-formatter`.

You can then achieve your desired result by importing `InputFormatter` and passing in your format.

```js
import {InputFormatter} from '@levidavidmurray/input-formatter';

InputFormatter({
  formats: { 10: 'xxx-xxx-xxxx' },
}).on('#input'); // replace with your input id
```

Closing this issue as it has been resolved. Thanks for the feedback!
